#PYTHON ARITHMETIC OPERATORS
# + ----> ADDTION
# - ----> SUBTRACTION
# / ----> DIVISION
# * ----> MULTIPLICATION
# % ----> MODULUS
# ** ---> EXPONENT

# x = 5 % 3  # MODULUS RETURNS REMAINDER AFTER DIVISION
# print(x)

# x = 5/3 # NORMAL DIVIION RETURNS A FLOAT DECIMAL VALUE
# print("NORMAL DIVISION : ", x)

# x = 5//3 # FLOOR DIVIION RETURNS AN INTEGER ROUNDED DOWN VALUE
# print(x)
# print("FLOOR DIVISION : ", x)

# x = 5 ** 3 # EXPONENT RAISES TO THE POWER
# print(x)
# print("EXPONENT OPERATOR : ", x)





#PYTHON ASSIGNMENT OPERATORS
# =  ----> BASIC ASSIGNMENT
# += ----> ADDTION & ASSIGN
# -= ----> SUBTRACTION & ASSIGN 
# /= ----> DIVISION & ASSIGN
# *= ----> MULTIPLICATION & ASSIGN


print("AT BASIC ASSIGNMENT\n\n")
APPLES = 6 # BASIC VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)


print("\n\nAT SUBTRACT AND ASSIGNMENT\n\n".upper())
APPLES -= 1 # SUBTRACTION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES -= 1 # ADDITION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES -= 1 # MULTIPLICATION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES -= 1 # DIVISION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES -= 1 # DIVISION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES -= 1 # DIVISION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)


print("\n\nAT ADD AND ASSIGNMENT\n\n")
APPLES += 1 # ADDITION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES += 1 # ADDITION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES += 1 # ADDITION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES += 1 # ADDITION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES += 1 # ADDITION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES += 1 # ADDITION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)


print("\n\nAT MULTIPLY AND ASSIGNMENT\n\n")
APPLES *= 2 # MULTIPLICATION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES *= 2 # MULTIPLICATION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES *= 2 # MULTIPLICATION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES *= 2 # MULTIPLICATION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES *= 2 # MULTIPLICATION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES *= 2 # MULTIPLICATION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)

print("\n\nAT DIVIDE AND ASSIGNMENT\n\n")
APPLES /= 2 # DIVISION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES /= 2 # DIVISION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES /= 2 # DIVISION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES /= 2 # DIVISION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES /= 2 # DIVISION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES /= 2 # DIVISION & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)

print("\n\nAT MODULUS AND ASSIGNMENT\n\n")
APPLES %= 10 # MODULUS & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES %= 10 # MODULUS & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES %= 10 # MODULUS & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES %= 10 # MODULUS & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES %= 10 # MODULUS & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES %= 10 # MODULUS & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)


print("\n\nAT EXPONENT AND ASSIGNMENT\n\n")
APPLES **= 2 # EXPONENT & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES **= 2 # EXPONENT & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES **= 2 # EXPONENT & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES **= 2 # EXPONENT & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES **= 2 # EXPONENT & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES **= 2 # EXPONENT & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)


print("\n\nAT FLOOR DIVIDE AND ASSIGNMENT\n\n")
APPLES //= 2 # FLOOR DIVIDE & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES //= 2 # FLOOR DIVIDE & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES //= 2 # FLOOR DIVIDE & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES //= 2 # FLOOR DIVIDE & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES //= 2 # FLOOR DIVIDE & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
APPLES //= 2 # FLOOR DIVIDE & VARIABLE ASSIGNMENT
print("APPLES : ", APPLES)
